version: "3.8"
services:
  goomba:
    image: goomba:latest
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    secrets:
      - discord_token
      - lavalink_password
    networks:
      - lavalink

secrets:
  discord_token:
    file: discord_token.txt
  lavalink_password:
    file: lavalink_password.txt

networks:
  lavalink:
    name: lavalink
    external: true